version: '3.1'
services:

  user_service-db:
    image: postgres:13.7-alpine
    container_name: user_service-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user

  user_service:
    build: .
    container_name: user_service
    ports:
      - "8081:8081"
    depends_on:
      - user_service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user_service-db:5432/user
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
